- name: conditional statements
  hosts: localhost
  vars:
    x: "krishna"
    val: 10
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: The value of x is krishna
      when: x=="krishna"
    - name: Task2
      ansible.builtin.debug:
        msg: The value of x is not krishna
      when: x!="krishna"
    - name: Task3
      ansible.builtin.debug:
        msg: The value of val is less than or equals to 10
      when: val | val<=10
    - name: Task4
      ansible.builtin.debug:
        msg: The value of val is greater than 10
      when: val | val>10