- name: conditional statements
  hosts: localhost
  vars:
    x: "krishna"
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: The value of x is krishna
      when: x=="krishna"
    - name: Task2
      ansible.builtin.debug:
        msg: The value of x is not krishna
      when: x!="krishna"