- name: conditional statements
  hosts: localhost
  vars:
    x: "krishna"
    val: 10
    b: true
    m: 12
    n: 15
    p: 25
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: The value of x is krishna
      when: x=="krishna"
    - name: Task2
      ansible.builtin.debug:
        msg: The value of x is not krishna
      when: x!="krishna"
    - name: Task3
      ansible.builtin.debug:
        msg: The value of val is less than or equals to 10
      when: val | int<=10
    - name: Task4
      ansible.builtin.debug:
        msg: The value of val is greater than 10
      when: val | int>10
    - name: Task5
      ansible.builtin.debug:
        msg: The value is true
      when: b | bool
    - name: task6
      ansible.builtin.debug:
        msg: The value is false
      when: not b | bool
    - name: task7
      ansible.builtin.debug:
        msg: "{{m}} is greatest number"
      when: m>n and m>p
    - name: task8
      ansible.builtin.debug:
        msg: "{{n}} is greatest number"
      when: n>m and n>p
    - name: task9
      ansible.builtin.debug:
        msg: "{{p}} is greatest number"
      when: p>m and p>n
