- name: Demo on Variables
  hosts: all
  vars:
    cname: BVRIT Hyderabad
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: "Task level variable- {{cname}}"
- name: File level Variables
  hosts: all
  vars_files:
    - variable_files.yml
  tasks:
    - name: Task2
      ansible.builtin.debug:
        msg: "This is file level variable- {{cname}}"
    - name: Task3
      ansible.builtin.debug:
        msg: "Location- {{Location}}"
- name: This is the play for task level varaibles
  hosts: all
  vars:
    cname: SKEC
  tasks:
    - name: Task level variable
      ansible.builtin.debug:
        msg: "The task level variable value is -{{cname}}"
      vars:
        cname: SVEC
    - name: Second task level variable
      ansible.builtin.debug:
        msg: "The variable will be play level variable-{{cname}}"