- name: Demo on Variables
  hosts: all
  vars:
    cname: BVRIT Hyderabad
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: "Task level variable- {{cname}}"
- name: File level Variables
  hosts: all
  v_files:
    - variable_files.yml
  tasks:
    - name: Task2
      ansible.builtin.debug:
        msg: "This is file level variable- {{cname}}"
    - name: Task3
      ansible.builtin.debug:
        msg: "Location- {{Location}}"