- name: demo on simple playbook
  hosts: all
  vars:
    a: 20
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: 'Welcome to first ansible playbook'
    - name: Task2
      ansible.builtin.debug:
        msg: "This is second statement"
    - name: Task3
      ansible.builtin.debug:
        msg: This is the value printing statement {{a}}