#- name: front end setup
#  become: yes
#  hosts: FRONTEND
#  roles:
#    - frontend
- name: mongodb setup
  become: yes
  hosts: MONGODB
  roles:
    - mongodb
#- name: catalogue setup
#  become: yes
#  hosts: CATALOGUE
#  roles:
#    - catalogue