#Erlang is a dependency which is needed for RabbitMQ.
#  # yum install https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm -y
#Setup YUM repositories for RabbitMQ.
#  # curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash
#Install RabbitMQ
#  # yum install rabbitmq-server -y
#Start RabbitMQ
#  # systemctl enable rabbitmq-server
#  # systemctl start rabbitmq-server
#RabbitMQ comes with a default username / password as guest/guest. But this user cannot be used to connect. Hence we need to create one user for the application.
#
#Create application user
## rabbitmqctl add_user roboshop roboshop123
## rabbitmqctl set_user_tags roboshop administrator
## rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
- name: configure yum repos for rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash
- name: Install erlang and rabbitmq
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
    state: present
- name: Start rabbitmq service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
